// 카테고리별 상품 데이터. price는 정가, discount는 할인율(%), sales는 누적 판매량.
// photo가 있으면 Unsplash 사진을, art/album이 있으면 product-art.js의 일러스트를 사용한다.

const CATEGORY_DATA = {
  fashion: {
    eyebrow: 'VINTAGE FASHION',
    title: '패션',
    description: '검수를 마친 빈티지 의류를 종류별로 골라보세요.',
    filters: [{ key: 'sub', label: '종류', options: ['티셔츠', '반바지', '스웨터', '후드티', '후드집업', '청바지', '아우터'] }],
    products: [
      { name: '90s 빈티지 포켓 티셔츠', sub: '티셔츠', shop: 'ARCHIVE CLOSET', condition: 'VERY GOOD', price: 22000, discount: 10, sales: 184, option: 'L', art: { shape: 'tshirt', color: '#c9b79c' } },
      { name: '레트로 링거 티셔츠', sub: '티셔츠', shop: 'MONO MARKET', condition: 'LIKE NEW', price: 18000, discount: 0, sales: 96, option: 'M', art: { shape: 'tshirt', color: '#ece3d1', accent: '#b5563f' } },
      { name: '워싱 데님 반바지', sub: '반바지', shop: 'ARCHIVE CLOSET', condition: 'GOOD', price: 26000, discount: 20, sales: 132, option: '30', art: { shape: 'shorts', color: '#6d84a3' } },
      { name: '치노 버뮤다 반바지', sub: '반바지', shop: 'MONO MARKET', condition: 'VERY GOOD', price: 24000, discount: 5, sales: 58, option: '32', art: { shape: 'shorts', color: '#c2ad86' } },
      { name: '피셔맨 케이블 스웨터', sub: '스웨터', shop: 'ARCHIVE CLOSET', condition: 'VERY GOOD', price: 48000, discount: 15, sales: 211, option: 'FREE', art: { shape: 'sweater', color: '#e3d6bd', accent: '#bfae8e' } },
      { name: '노르딕 패턴 울 스웨터', sub: '스웨터', shop: 'ODD OBJECTS', condition: 'GOOD', price: 42000, discount: 30, sales: 77, option: 'M', art: { shape: 'sweater', color: '#7a3b2e', accent: '#e8d9b8' } },
      { name: '오버핏 그레이 후드티', sub: '후드티', shop: 'MONO MARKET', condition: 'GOOD', price: 32000, discount: 0, sales: 156, option: 'XL', art: { shape: 'hoodie', color: '#9a958c' } },
      { name: '칼리지 로고 후드티', sub: '후드티', shop: 'ARCHIVE CLOSET', condition: 'VERY GOOD', price: 39000, discount: 25, sales: 243, option: 'L', art: { shape: 'hoodie', color: '#2f3a4a', accent: '#e1b25c' } },
      { name: '헤비 코튼 후드집업', sub: '후드집업', shop: 'MONO MARKET', condition: 'VERY GOOD', price: 44000, discount: 10, sales: 119, option: 'L', art: { shape: 'zipup', color: '#5d6b4f' } },
      { name: '버건디 스웻 후드집업', sub: '후드집업', shop: 'ODD OBJECTS', condition: 'GOOD', price: 36000, discount: 35, sales: 64, option: 'M', art: { shape: 'zipup', color: '#7b2f2b' } },
      { name: '90s 스트레이트 청바지', sub: '청바지', shop: 'ARCHIVE CLOSET', condition: 'VERY GOOD', price: 52000, discount: 20, sales: 298, option: '31', art: { shape: 'jeans', color: '#4a6488' } },
      { name: '라이트 워싱 와이드 청바지', sub: '청바지', shop: 'MONO MARKET', condition: 'GOOD', price: 46000, discount: 0, sales: 141, option: '29', art: { shape: 'jeans', color: '#8ca3bf' } },
      { name: '90s 스웨이드 재킷', sub: '아우터', shop: 'ARCHIVE CLOSET', condition: 'VERY GOOD', price: 88000, discount: 30, sales: 187, option: 'M', photo: '1551028719-00167b16eac5' },
      { name: '헤링본 울 블레이저', sub: '아우터', shop: 'ODD OBJECTS', condition: 'VERY GOOD', price: 72000, discount: 15, sales: 92, option: 'L', art: { shape: 'jacket', color: '#8a7a66' } },
      { name: '코듀로이 트러커 재킷', sub: '아우터', shop: 'MONO MARKET', condition: 'GOOD', price: 64000, discount: 5, sales: 128, option: 'M', art: { shape: 'jacket', color: '#a8743f', accent: '#e8d9b8' } },
    ],
  },
  electronics: {
    eyebrow: 'VINTAGE ELECTRONICS',
    title: '전자기기',
    description: '작동 여부까지 확인한 카메라, 오디오, 빈티지 전자기기입니다.',
    filters: [{ key: 'sub', label: '종류', options: ['카메라', '오디오', '컴퓨터·게임', '조명'] }],
    products: [
      { name: '올림푸스 필름 카메라', sub: '카메라', shop: 'MONO MARKET', condition: 'GOOD', price: 86000, discount: 10, sales: 164, option: '작동 확인', photo: '1516035069371-29a1b244cc32' },
      { name: '레인지파인더 필름 카메라', sub: '카메라', shop: 'MONO MARKET', condition: 'VERY GOOD', price: 124000, discount: 0, sales: 71, option: '작동 확인', art: { shape: 'camera', color: '#3d3a35' } },
      { name: '하프 프레임 카메라', sub: '카메라', shop: 'ODD OBJECTS', condition: 'GOOD', price: 68000, discount: 20, sales: 103, option: '렌즈 포함', art: { shape: 'camera', color: '#8a6a4f' } },
      { name: '우드 패널 트랜지스터 라디오', sub: '오디오', shop: 'ROOM 204', condition: 'GOOD', price: 58000, discount: 15, sales: 88, option: 'AM/FM', art: { shape: 'radio', color: '#8a6a4f' } },
      { name: '포터블 카세트 플레이어', sub: '오디오', shop: 'MONO MARKET', condition: 'VERY GOOD', price: 74000, discount: 5, sales: 192, option: '작동 확인', art: { shape: 'cassette', color: '#c9b79c' } },
      { name: '오버이어 헤드폰', sub: '오디오', shop: 'ROOM 204', condition: 'LIKE NEW', price: 62000, discount: 25, sales: 136, option: '유선', photo: '1505740420928-5e560c06d30e' },
      { name: '레트로 온이어 헤드폰', sub: '오디오', shop: 'ODD OBJECTS', condition: 'GOOD', price: 34000, discount: 0, sales: 57, option: '유선', art: { shape: 'headphones', color: '#b5563f' } },
      { name: '빈티지 노트북', sub: '컴퓨터·게임', shop: 'MONO MARKET', condition: 'GOOD', price: 160000, discount: 25, sales: 42, option: '초기화 완료', photo: '1525547719571-a2d4ac8945e2' },
      { name: '레트로 기계식 키보드', sub: '컴퓨터·게임', shop: 'ROOM 204', condition: 'VERY GOOD', price: 82000, discount: 10, sales: 118, option: '유선', art: { shape: 'keyboard', color: '#d9d4c8', accent: '#f6f1e6' } },
      { name: '레트로 휴대용 게임기', sub: '컴퓨터·게임', shop: 'ODD OBJECTS', condition: 'GOOD', price: 96000, discount: 0, sales: 205, option: '작동 확인', art: { shape: 'handheld', color: '#d8d2c4' } },
      { name: '유리 테이블 램프', sub: '조명', shop: 'ROOM 204', condition: 'GOOD', price: 42000, discount: 15, sales: 97, option: '높이 32cm', photo: '1507473885765-e6ed057f782c' },
      { name: '패브릭 쉐이드 램프', sub: '조명', shop: 'ROOM 204', condition: 'VERY GOOD', price: 38000, discount: 5, sales: 66, option: '높이 40cm', art: { shape: 'lamp', color: '#e3cfa8' } },
      { name: '미드센추리 무드등', sub: '조명', shop: 'ODD OBJECTS', condition: 'LIKE NEW', price: 46000, discount: 30, sales: 149, option: '높이 28cm', art: { shape: 'lamp', color: '#b5563f' } },
    ],
  },
  cd: {
    eyebrow: 'MUSIC ARCHIVE 1990—2026',
    title: 'CD',
    description: '1990년 클래식 앨범부터 2026년 아이돌 앨범까지, 장르와 연대별로 찾아보세요.',
    filters: [
      { key: 'genre', label: '장르', options: ['클래식', '발라드', '팝', 'K팝'] },
      { key: 'era', label: '연대', options: ['1990년대', '2000년대', '2010년대', '2020년대'] },
    ],
    products: [
      { name: '골드베르크 변주곡', artist: '한서윤', genre: '클래식', year: 1993, shop: 'SOUND SHELF', condition: 'VERY GOOD', price: 24000, discount: 10, sales: 62, option: '1CD', album: { color: '#2f3a4a', accent: '#e1b25c', pattern: 0 } },
      { name: '비발디 사계', artist: '서울 바로크 앙상블', genre: '클래식', year: 2004, shop: 'SOUND SHELF', condition: 'LIKE NEW', price: 18000, discount: 0, sales: 88, option: '1CD', album: { color: '#5d6b4f', accent: '#efe3c8', pattern: 5 } },
      { name: '베토벤 교향곡 전집', artist: '노을 필하모닉', genre: '클래식', year: 2015, shop: 'SOUND SHELF', condition: 'VERY GOOD', price: 46000, discount: 20, sales: 41, option: '5CD 박스', album: { color: '#7a3b2e', accent: '#e8d9b8', pattern: 1 } },
      { name: '쇼팽 녹턴 선집', artist: '이도윤', genre: '클래식', year: 2024, shop: 'SOUND SHELF', condition: 'LIKE NEW', price: 22000, discount: 5, sales: 73, option: '1CD', album: { color: '#1f2a36', accent: '#c9b79c', pattern: 2 } },
      { name: '겨울비 내리는 밤', artist: '윤하람', genre: '발라드', year: 1996, shop: 'RECORD 90', condition: 'GOOD', price: 16000, discount: 15, sales: 154, option: '1CD', album: { color: '#6d84a3', accent: '#e5ecf2', pattern: 3 } },
      { name: '그 시절 우리', artist: '정서진', genre: '발라드', year: 2003, shop: 'RECORD 90', condition: 'VERY GOOD', price: 14000, discount: 0, sales: 121, option: '1CD', album: { color: '#c9a46c', accent: '#fff4dc', pattern: 2 } },
      { name: '오래된 편지', artist: '민결', genre: '발라드', year: 2012, shop: 'SOUND SHELF', condition: 'VERY GOOD', price: 15000, discount: 25, sales: 97, option: '1CD', album: { color: '#8a7a66', accent: '#efe3c8', pattern: 5 } },
      { name: '천천히, 다시', artist: '해온', genre: '발라드', year: 2022, shop: 'RECORD 90', condition: 'LIKE NEW', price: 19000, discount: 10, sales: 176, option: '1CD + 포토북', album: { color: '#b08d8a', accent: '#f6e8e4', pattern: 0 } },
      { name: 'Midnight Radio', artist: 'The Velvet Lines', genre: '팝', year: 1991, shop: 'RECORD 90', condition: 'GOOD', price: 21000, discount: 0, sales: 69, option: '수입반', album: { color: '#3d3a35', accent: '#b5563f', pattern: 4 } },
      { name: 'Summer Polaroid', artist: 'June & Co.', genre: '팝', year: 2007, shop: 'SOUND SHELF', condition: 'VERY GOOD', price: 17000, discount: 30, sales: 112, option: '수입반', album: { color: '#e1a35c', accent: '#fff1d6', pattern: 2 } },
      { name: 'Neon Hearts', artist: 'Ella Moore', genre: '팝', year: 2017, shop: 'RECORD 90', condition: 'LIKE NEW', price: 20000, discount: 10, sales: 138, option: '디럭스', album: { color: '#5b3a6b', accent: '#f0a8c0', pattern: 1 } },
      { name: 'Golden Hour Tapes', artist: 'Sunday Club', genre: '팝', year: 2025, shop: 'SOUND SHELF', condition: 'LIKE NEW', price: 23000, discount: 5, sales: 84, option: '수입반', album: { color: '#a3442f', accent: '#f3d58a', pattern: 3 } },
      { name: '첫사랑 신드롬', artist: '파란별', genre: 'K팝', year: 1998, shop: 'RECORD 90', condition: 'GOOD', price: 28000, discount: 0, sales: 203, option: '1집 초판', album: { color: '#4a7fb5', accent: '#fff4f0', pattern: 3 } },
      { name: 'Starlight Road', artist: 'NOVA9', genre: 'K팝', year: 2009, shop: 'RECORD 90', condition: 'VERY GOOD', price: 19000, discount: 15, sales: 167, option: '미니앨범', album: { color: '#2b2a28', accent: '#e1b25c', pattern: 4 } },
      { name: 'Wave Runner', artist: 'LUMINA', genre: 'K팝', year: 2019, shop: 'SOUND SHELF', condition: 'LIKE NEW', price: 22000, discount: 20, sales: 284, option: '포토카드 포함', album: { color: '#3f8f8a', accent: '#d9f2ee', pattern: 5 } },
      { name: 'ECHO:26', artist: 'ARIA:X', genre: 'K팝', year: 2026, shop: 'SOUND SHELF', condition: 'SEALED', price: 26000, discount: 0, sales: 312, option: '미개봉', album: { color: '#d96c8a', accent: '#fff0f4', pattern: 0 } },
    ],
  },
  props: {
    eyebrow: 'VINTAGE OBJECTS',
    title: '소품',
    description: '인테리어 소품부터 책상, 컴퓨터, 냉장고에 두기 좋은 미니멀 소품까지.',
    filters: [{ key: 'sub', label: '종류', options: ['인테리어 소품', '데스크 소품', '컴퓨터 소품', '냉장고 소품', '수납·정리', '키친·테이블'] }],
    products: [
      { name: '빈티지 플라워 베이스', sub: '인테리어 소품', shop: 'ODD OBJECTS', condition: 'LIKE NEW', price: 38000, discount: 15, sales: 142, option: '1개', art: { shape: 'vase', color: '#c9774f', accent: '#f3e3cf' } },
      { name: '세라믹 미니 화병', sub: '인테리어 소품', shop: 'ODD OBJECTS', condition: 'VERY GOOD', price: 21000, discount: 0, sales: 88, option: '높이 18cm', art: { shape: 'vase', color: '#7b8b6f', accent: '#efe3c8' } },
      { name: '소이 캔들 & 황동 홀더', sub: '인테리어 소품', shop: 'ROOM 204', condition: 'LIKE NEW', price: 18000, discount: 10, sales: 176, option: '1세트', art: { shape: 'candle', color: '#efe3c8' } },
      { name: '빈티지 우드 액자', sub: '인테리어 소품', shop: 'ROOM 204', condition: 'GOOD', price: 16000, discount: 20, sales: 64, option: 'A5', art: { shape: 'frame', color: '#8a6a4f' } },
      { name: '테라코타 화분', sub: '인테리어 소품', shop: 'ODD OBJECTS', condition: 'VERY GOOD', price: 14000, discount: 0, sales: 99, option: '지름 12cm', art: { shape: 'plant', color: '#c9774f' } },
      { name: '레트로 벽시계', sub: '인테리어 소품', shop: 'ROOM 204', condition: 'GOOD', price: 34000, discount: 25, sales: 53, option: '작동 확인', art: { shape: 'clock', color: '#5d6b4f' } },
      { name: '오크 원목 사이드 테이블', sub: '인테리어 소품', shop: 'ROOM 204', condition: 'GOOD', price: 52000, discount: 20, sales: 47, option: '직거래', photo: '1499933374294-4584851497cc' },
      { name: '미니멀 펜 홀더', sub: '데스크 소품', shop: 'MONO MARKET', condition: 'LIKE NEW', price: 9000, discount: 0, sales: 231, option: '1개', art: { shape: 'pencup', color: '#d9d4c8' } },
      { name: '원목 데스크 선반', sub: '데스크 소품', shop: 'ROOM 204', condition: 'VERY GOOD', price: 32000, discount: 10, sales: 118, option: '폭 45cm', art: { shape: 'shelf', color: '#c2a27a' } },
      { name: '스틸 북엔드 세트', sub: '데스크 소품', shop: 'MONO MARKET', condition: 'GOOD', price: 15000, discount: 30, sales: 82, option: '2개 세트', art: { shape: 'bookend', color: '#3d3a35' } },
      { name: '라탄 데스크 트레이', sub: '데스크 소품', shop: 'ODD OBJECTS', condition: 'VERY GOOD', price: 13000, discount: 5, sales: 69, option: '1개', art: { shape: 'tray', color: '#c9a46c' } },
      { name: '레트로 키캡 세트', sub: '컴퓨터 소품', shop: 'MONO MARKET', condition: 'LIKE NEW', price: 28000, discount: 15, sales: 194, option: '5개입', art: { shape: 'keycap', color: '#e5dccb', accent: '#c9b79c' } },
      { name: '코르크 마우스패드', sub: '컴퓨터 소품', shop: 'MONO MARKET', condition: 'LIKE NEW', price: 12000, discount: 0, sales: 157, option: '30×22cm', art: { shape: 'mousepad', color: '#b08d62' } },
      { name: '케이블 정리 클립', sub: '컴퓨터 소품', shop: 'ODD OBJECTS', condition: 'SEALED', price: 7000, discount: 10, sales: 268, option: '5구', art: { shape: 'cableclip', color: '#7b8b6f', accent: '#e5dccb' } },
      { name: '모니터 받침 선반', sub: '컴퓨터 소품', shop: 'ROOM 204', condition: 'VERY GOOD', price: 36000, discount: 20, sales: 91, option: '폭 60cm', art: { shape: 'shelf', color: '#8a6a4f' } },
      { name: '빈티지 마그넷 세트', sub: '냉장고 소품', shop: 'ODD OBJECTS', condition: 'LIKE NEW', price: 11000, discount: 0, sales: 213, option: '4개입', art: { shape: 'magnets', color: '#b5563f', accent: '#cfd8c0' } },
      { name: '코르크 메모 보드', sub: '냉장고 소품', shop: 'MONO MARKET', condition: 'VERY GOOD', price: 14000, discount: 15, sales: 76, option: '자석 부착형', art: { shape: 'memoboard', color: '#b08d62' } },
      { name: '빈티지 틴 수납함', sub: '수납·정리', shop: 'ODD OBJECTS', condition: 'GOOD', price: 17000, discount: 10, sales: 58, option: '중형', art: { shape: 'box', color: '#5d6b4f', accent: '#efe3c8' } },
      { name: '패브릭 리빙 박스', sub: '수납·정리', shop: 'ROOM 204', condition: 'VERY GOOD', price: 19000, discount: 25, sales: 104, option: '대형', art: { shape: 'box', color: '#c9b79c', accent: '#fffaf2' } },
      { name: '세라믹 플레이트 2장', sub: '키친·테이블', shop: 'ODD OBJECTS', condition: 'LIKE NEW', price: 18000, discount: 10, sales: 133, option: '2개 세트', photo: '1493106641515-6b5631de4bb9' },
      { name: '빈티지 유리잔 세트', sub: '키친·테이블', shop: 'GLASS ARCHIVE', condition: 'VERY GOOD', price: 28000, discount: 20, sales: 162, option: '2개 세트', photo: '1470337458703-46ad1756a187' },
      { name: '에나멜 머그컵', sub: '키친·테이블', shop: 'MONO MARKET', condition: 'GOOD', price: 12000, discount: 0, sales: 87, option: '350ml', art: { shape: 'mug', color: '#efe3c8', accent: '#2f3a4a' } },
    ],
  },
};
